version: '3'
services:
  database:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - fastapidb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_DB: fastapi
      TZ: America/Sao_Paulo
volumes:
  fastapidb: