version: '3'
services:
  database:
    image: postgres:12.1
    restart: unless-stopped
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_DB: fastapi
      POSTGRES_PASSWORD: 123mudar
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    env_file: .env
    depends_on:
      - database
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: [
      "sh",
      "-c",
      "pipenv run alembic upgrade head | pipenv run uvicorn app:api --reload --host '0.0.0.0' --port '5000'"
    ]
  app-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    env_file: .env.testing
    volumes:
      - .:/app
    entrypoint: ["sh", "/scripts/run-tests.sh"]
